version: "3"

services:
  frontend:
    build: 
      context: .
    volumes:
      - ./simple_pomodoro_timer/:/usr/src/app
    command: sh -c 'yarn start'
    ports:
      - "3000:3000"
    tty: true
